minio:
  endpoint: http://q49bec96.natappfree.cc
#  endpoint: http://127.0.0.1:9000
  accessKey: minioadmin
  secretKey: minioadmin
server:
  port: 8081
spring:
  servlet:
    multipart:
      max-file-size: 20000MB
      max-request-size: 20000MB
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/lianxi?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志
